version: '3.8'
services:
  rapid-ride:
    build: ../rapidride
    image: rr_image
    container_name: rr_container
    ports:
      - "9090:9090"
    depends_on:
      - rapid-ride-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://rapid-ride-db:5432/rapid-ride
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123
      - POSTGRES_DB=rapid-ride
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123

  rapid-ride-db:
    image: postgres:latest
    container_name: rapid-ride-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=rapid-ride
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123

  kafka:
    image: docker.io/bitnami/kafka:3.7
    container_name: kafka
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      # KRaft settings
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      # Listeners
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT

  minio:
    image: docker.io/bitnami/minio:2024
    container_name: minio
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - 'minio_data:/bitnami/minio/data'

volumes:
  kafka_data:
    driver: local

  minio_data:
    driver: local
