version: '3.8'
services:
  rapid-ride:
    build: ../rapidride
    image: rr_image
    container_name: rr_container
    ports:
      - "9090:9090"
    depends_on:
      - rapid-ride-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://rapid-ride-db:5432/rapid-ride
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123
      - POSTGRES_DB=rapid-ride
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123

  rapid-ride-db:
    image: postgres:latest
    container_name: rapid-ride-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=rapid-ride
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123

  minio:
    image: docker.io/bitnami/minio:2024
    container_name: minio
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - 'minio_data:/bitnami/minio/data'
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin

volumes:
  kafka_data:
    driver: local

  minio_data:
    driver: local
